# Generated by Django 4.2.24 on 2025-11-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[(2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years')], default=4),
        ),
    ]
